name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      k3s:
        image: debianmaster/k3s
        ports:
        - 6443:6443
        volumes:
        - /tmp:/output
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - run: ls -lrt
    - run: KUBECONFIG=/tmp/output kubectl get nodes
    - run: curl -k https://localhost:6443/healthz
