name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: rancher/k3s:latest
        ports:
        - 6443:6443
        options: server
        env:
          K3S_TOKEN: "mytoken"
          K3S_KUBECONFIG_OUTPUT: "/output/kubeconfig.yaml"
          K3S_KUBECONFIG_MODE: "666"

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      
    - run: kubectl get po -A
      env:
        KUBECONFIG: "/output/kubeconfig.yaml"
