name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      k3s:
        image: debianmaster/k3s
        ports:
        - 6443:6443

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      
    - run: curl -k https://localhost:6443/healthz
