
name: CI

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: debianmaster/actions-k3s@master
      id: k3s
      with:
        version: 'v0.9.1'
    - run: |
        kubectl get nodes
        kubectl get pods -A
        sleep 20
        kubectl get pods -A
    - name: pycodestyle
      uses: ankitvgupta/pycodestyle-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PRECOMMAND_MESSAGE: You have style errors. See them below.
        
        
        
