name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k3s-version: [0.9.1, 1.0.0]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Start k3s
      uses: debianmaster/k3s-github-action@master
      with:
        k3s-version: ${{ matrix.k3s-version }}

    - run: kubectl get po -A
