name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      k3s:
        image: debianmaster/k3s
        ports:
        - 6443:6443
        volumes:
        - /tmp/output:/output
        options: --privileged	
      k3s-091:
        image: debianmaster/k3s
        ports:
        - 7443:6443
        volumes:
        - /tmp/k3s-091:/output
        options: --privileged	
    steps:
      
    - name: deploy to cluster
      uses: debianmaster/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with: |
        export KUBECONFIG=/tmp/output/kubeconfig.yaml
        kubectl kuttle -h
        kubectl get nodes
    - name: test2
      run: |
        kubectl krew update
        sleep 20
        export KUBECONFIG=/tmp/output/kubeconfig.yaml
        kubectl get nodes

        sleep 20
        export KUBECONFIG=/tmp/k3s-091/kubeconfig.yaml
        kubectl get nodes

