
name: CI


on:
  push:
    branches: [ develop ]


jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: debianmaster/hello-world-javascript-action@master
      with:
        version: 'v0.9.1'
    - run: |
        docker ps
        
