
name: CI

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: debianmaster/hello-world-javascript-action@master
      id: k3s
      with:
        version: 'v0.9.1'
    - run: |
        docker ps
        echo ${{ steps.k3s.outputs.kubeconfig }}
        kubectl get nodes
        
