name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      k3s:
        image: debianmaster/k3s
        ports:
        - 6443:6443
        volumes:
        - /tmp/output:/output
        options: --privileged	
    steps:
    - run: docker ps
    - run: sleep 10
    - run: docker ps
    - run: ls -lrt /tmp/output
    - run: cat /tmp/output/kubeconfig.yaml
    - run: docker ps
    - run: KUBECONFIG=/tmp/output/kubeconfig.yaml kubectl get nodes
    - run: curl -k https://localhost:6443/healthz
