# This is a basic workflow to help you get started with Actions

name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      uses: debianmaster/action-kubectl@0.0.1
      with:
        token: test
