# This is a basic workflow to help you get started with Actions

name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [0.9.1,1.0]
    steps:
    - name: Install doctl
      run: |
        echo ${{ matrix.k8s_version }}
