# This is a basic workflow to help you get started with Actions

name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [v0.9.1]
    steps:
    - name: Install doctl
      run: |
        KUBECONFIG=/tmp/output/kubeconfig-${{ matrix.k8s_version }}.yaml
        K3S_VERSION=${{ matrix.k8s_version }}
        
        echo "K3S_TOKEN=mytoken" > .env
        echo "K3S_KUBECONFIG_OUTPUT=${KUBECONFIG}" >> .env
        echo "K3S_KUBECONFIG_MODE=666" >> .env 
        cat .env
        
        docker run -d --privileged --name	k3s-${K3S_VERSION} --env-file .env -v /tmp/output:/output -p 6443:6443 rancher/k3s:${K3S_VERSION} server 
        wait_file() {
          local file="$1"; shift
          local wait_seconds="${1:-10}"; shift # 10 seconds as default timeout

          until test $((wait_seconds--)) -eq 0 -o -f "$file" ; do sleep 1; done

          ((++wait_seconds))
        }
        wait_file "$KUBECONFIG" 15 || {
          echo "file missing after waiting for $? seconds: '$server_log'"
          exit 1
        }      
        
        kubectl get nodes
        kubectl get po -A
        
        
