# This is a basic workflow to help you get started with Actions

name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [0.9.1,1.0]
    steps:
    - name: Install doctl
      run: |
        echo ${{ matrix.k8s_version }}
        K3S_TOKEN=mytoken
        K3S_KUBECONFIG_OUTPUT=/output/kubeconfig-${{ matrix.k8s_version }}.yaml
        K3S_KUBECONFIG_MODE=666
        docker run -d --privileged 6443:6443 rancher/k3s:${{ matrix.k8s_version }}
        docker ps
        ls /output/
        sleep 10
        ls /output/
        
        
