# This is a basic workflow to help you get started with Actions

name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [v0.9.1]
    steps:
    - name: Install doctl
      run: |
        echo ${{ matrix.k8s_version }}
        K3S_TOKEN=mytoken
        K3S_KUBECONFIG_OUTPUT=/output/kubeconfig-${{ matrix.k8s_version }}.yaml
        K3S_KUBECONFIG_MODE=666
        docker run -d --privileged -v /tmp/output:/output -p 6443:6443 rancher/k3s:${{ matrix.k8s_version }}
        docker ps
        sleep 20
        ls /output/
        export KUBECONFIG=/tmp/output/kubeconfig-${{ matrix.k8s_version }}.yaml
        kubectl get nodes
        kubectl get po -A
        
        
